version: '3.8'

services:

  higiea_app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/higiea_db
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017
      MQTT_BROKER_URL: tcp://mosquitto:1883

    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mosquitto
      - mongodb

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: higiea_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mosquitto:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_config:/mosquitto/config

  mongodb:
    image: mongo:8.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mosquitto_data:
  mongo_data:
  mosquitto_config: